# -*- coding: utf-8 -*-
"""exercicio-estrutura-condicional.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nedk20hUb0l-UJzfbn9jPOhDMeK4uwoG
"""

# Leia dois números, faça a soma e apresente caso seja maior que 15

n1 = float(input('Digite primeiro valor: '))
n2 = float(input('Digite o segundo valor: '))

soma = n1 + n2

if soma > 15:
  print(f'A soma dos valores {n1:.0f} + {n2:.0f} resultou em: {soma}')
else:
  print('Soma feita!')

# Faça um programa que recebendo um valor inteiro, informe se o número é positivo, negativo ou neutro.

print('- ' * 10)
print('\033[1;36mVerificando valores\033[0m')
print('- ' * 10)

valor = int(input('\nDigite um valor: '))

if valor > 0:
  print(f'O valor {valor} é \033[32mpositivo\033[0m.')
elif valor == 0:
  print(f'O valor {valor} é \033[1mneutro\033[m')
else:
  print(f'O valor {valor} é \033[31mnegativo\033[0m')

# Leia a idade e informe se a pessoa é maior ou menor de idade

idade = int(input('Digite a idade da pessoa: '))

if idade >= 18:
  print('Maior de idade.')
else:
  print('Menor de idade')

# Faça um programa que pergunte a temperatura atual para o usuário e mostre uma mensagem na tela dizendo se está “quente”, “frio” ou “agradável”

temperatura = float(input('Digite a temperatura atual do ambiente: '))

if temperatura > 25:
  print(f'O clima de {temperatura:.1f}° é considerado \033[31mquente\033[m!')
elif temperatura > 19 and temperatura < 26:
  print(f'O clima de {temperatura:.1f}° é considerado \033[33magradável\033[m!')
else:
  print(f'O clima de {temperatura:.1f}° é considerado \033[34mfrio\033[m!')

# Faça um programa em linguagem Python que leia dois números inteiros e informe se estes são iguais ou diferentes.

n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))

if n1 == n2:
  print('\nOs números inseridos são iguais!')
else:
  print('\nOs números inseridos são diferentes!')

# Escreva um programa que verifique a validade de uma senha fornecida pelo usuário. A senha válida é o número 1234. Devem ser impressas as seguintes mensagens:
# ACESSO PERMITIDO caso a senha seja válida.
# ACESSO NEGADO caso a senha seja inválida

print('-' * 20)
print('\033[1;35m Acesse a sua conta\033[0m')
print('-' * 20)

senha = 1234

x = int(input('\nDigite sua senha: '))

if x == senha:
  print('\033[1;32mACESSO PERMITIDO\033[0m')
else:
  print('\033[1;31mACESSO NEGADO\033[0m')

# Ler duas notas de um aluno, efetuar a média aritmética
# Se a média for maior ou igual a 7 informar que o aluno foi aprovado;
# Se a média for maior ou igual a 5 mas menor do que 7, informar que o aluno está de exame;
# Se a média for menor do que 5 informar que o aluno foi reprovado.

#Lendo a primeira nota
n1 = float(input('Digite a primeira nota: '))
#Lendo a segunda nota
n2 = float(input('Digite a segunda nota: '))

#Realizando a média
media = (n1+n2) / 2

#Estrutura de lógica
if media >= 7:
  #Se a média for maior ou igual à 7, a situação será Aprovado.
  situacao = 'Aprovado'
  #Imprimindo
  print(f'O aluno está \033[1;32m{situacao}\033[0m!')
elif media >= 5 and media < 7:
    #Se a média for maior ou igual à 5 e menor que 7, a situação será Em exame.
  situacao = 'Em exame'
  #Imprimindo
  print(f'O aluno está \033[1;33m{situacao}\033[0m!')
else:
    #Se a média for menor que 5, a situação será Reprovado.
  situacao = 'Reprovado'
  #Imprimindo
  print(f'O aluno foi \033[1;31m{situacao}\033[0m!')

# Desenvolva um programa que recebe do usuário o placar de um jogo de futebol (os gols de cada time)
# Informe se o resultado foi um empate, se a vitória foi do primeiro time ou do segundo time.

#Lendo o nome do primeiro time
time1 = str(input('Digite o nome do primeiro time: '))
#Quantidade de gols que o time 1 marcou
gol_time1 = int(input('Quantidades de gol em que o time marcou: '))
#Lendo o nome do segundo time
time2 = str(input('Digite o nome do segundo time: '))
#Quantidade de gols que o time 2 marcou
gol_time2 = int(input('Quantidades de gol em que o time marcou: '))

#Estrutura de lógica
if gol_time1 > gol_time2:
  #Se o time 1 marcou mais gols, vitoria recebe time 1
  vitoria = time1
  #Imprimindo
  print(f'O time \033[1;36m{time1}\033[0m ganhou!')
elif gol_time1 == gol_time2:
  #Se o resultado dos gols ser igual, vitoria recebe empate
  vitoria = 'Empate'
  #Imprimindo
  print(f'A situação do jogo foi \033[1;33m{vitoria}\033[0m.')
else:
    #Se o resultado não for nem um e nem outro, imprime
    print(f'O time \033[1;36m{time2}\033[0m ganhou!')

# Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N-Noturno.
# Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso.

#Define a variável com o turno de estudo do estudante.
turno = str(input('Digite o turno em que você estuda:\n[ M ] Matutino\n[ V ] Vespertino\n[ N ] Noturno\n\n')).upper()[0]
if turno == 'M':
  #Definindo periodo
  periodo = 'Matutino'
  print('Bom Dia!')
elif turno == 'V':
  #Definindo periodo
  periodo = 'Vespertino'
  print('Boa Tarde!')
elif turno == 'N':
  #Definindo periodo
  periodo = 'Noturno'
  print('Boa Noite!')
else:
  periodo = 'Valor Inválido'
  print('Valor Inválido!')

# Faça um programa que solicite ao usuário sua idade, depois disso, exiba a classificação etária de acordo com as faixas de valores:
# Criança para 0 até 11 anos;
# Adolescente para 12 até 18 anos;
# Jovem para 19 até 24 anos;
# Adulto para 25 até 40 anos;
# Meia Idade para 41 até 60 anos;
# Idoso acima de 60 anos.

nome = str(input('Digite o nome: '))
idade = int(input(f'Digite a idade de {nome}: '))

if idade >=12 and idade <= 18:
  situacao = 'Adolescente'
elif idade >= 19 and idade <= 24:
  situacao = 'Jovem'
elif idade >= 25 and idade <= 40:
  situacao = 'Adulto'
elif idade >= 41 and idade <= 60:
  situacao = 'Meia Idade'
elif idade > 60:
  situacao = 'Idoso'
else:
  situacao = 'Criança'

print(f'{nome} tem {idade} anos de idade e sua classificação etária é {situacao}.')

# As Organizações Tabajara resolveram dar um aumento de salário aos seus colaboradores e lhe contrataram para desenvolver o programa que calculará os reajustes.
# Faça um programa que recebe o salário de um colaborador e o reajuste segundo o seguinte critério, baseado no salário atual:
# salários até R$ 280,00 (incluindo) : aumento de 20%
# salários entre R$ 700,00 e R$ 1500,00 : aumento de 10%
# salários de R$ 1500,00 em diante : aumento de 5%

# Após o aumento ser realizado, informe na tela:
# o salário antes do reajuste;
# o percentual de aumento aplicado;
# o novo salário, após o aumento.

print('-=-'*7)
print('Organizações Tabajara')
print('-=-'*7)

nome = str(input('Digite o nome do funcionário: '))
salario = float(input(f'Digite o salário do (a) {nome}: '))

#Salários até R$280
if salario <= 280:
  #Porcentagem
  p = 0.2
  #Quantidade da porcntagem dentro do salário
  soma = salario * p
  #Somando os valores
  salario_up = salario + soma
elif salario >= 700 and salario <= 1500:
  #Porcentagem
  p = 0.1
  #Quantidade de 10% do salário
  soma = salario * p
  #Somando os valores
  salario_up = salario + soma
else:
  #Porcentagem
  p = 0.05
  #Quantidade de 5% do salário
  soma = salario * p
  #Somando os valores
  salario_up = salario + soma

#Informando os dados
print(f'Os dados sobre o funcionário {nome}\n\n'
      f'Salário Base: \033[32mR${salario:.2f}\033[0m\n'
      f'Percentual de aumento: \033[32m{p*100}%\033[0m\n'
      f'Salário atual: \033[1;32mR${salario_up:.2f}\033[0m')

#  Faça um Programa que leia um número e exiba o dia correspondente da semana.
# (1-Domingo, 2- Segunda, etc.), se digitar outro valor deve aparecer valor inválido.

semana = ['Domingo', 'Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado']

dia = int(input('Digite o dia da semana conforme o requisitado:\n\n'
                '[1] Domingo\n[2] Segunda-Feira\n[3] Terça-Feira\n[4] Quarta-Feira\n[5] Quinta-Feira\n[6] Sexta-Feira\n[7] Sábado\n\n'))

if dia > 0 and dia <= 7:
  print(f'O dia da semana escolhido foi {semana[dia-1]}')
else:
  print('Valor Inválido')

# Faça um programa que pergunte ao usuário se ele quer passar uma temperatura de Fahrenheit para Celsius ou de Celsius para Fahrenheit
# A partir da resposta do usuário, faça a devida conversão.

opcao = int(input('Qual dos dados deseja inserir?\n'
                  '[1] Fahrenheit\n'
                  '[2] Celsius\n\n'))

temperatura = float(input('Digite a temperatura: º'))

#Operação de Fahrenheit para Celsius
if opcao == 1:
  temperatura -= 32
  convertido = temperatura / 1.8
  print(f'O valor em graus em Fahrenheit para Celsius é resultado em {convertido:.1f}º ')
elif opcao == 2:
  temperatura *= 1.8
  convertido = temperatura + 32
  print(f'O valor em graus em Celsius para Fahrenheit é resultado em {convertido:.1f}º ')
else:
  print('Valor Inválido')

# Faça um programa que receba a idade de uma pessoa e imprima sua condição
# (Obrigatória, optativa ou proibida), em relação ao ato de votar, conforme apresentado abaixo:

# Pessoas com idade menor que 16 anos são proibidas de votar (proibido);
# Pessoas com idade igual a 16 e menor que 18 anos não são obrigadas a votar (optativo);
# Pessoas com idade igual a 18 e menor que 65 anos são obrigadas a votar (obrigatório);
# Pessoas com idade igual ou maior a 65 anos não são obrigadas a votar (optativo).

nome = str(input('Digite o nome: '))
idade = int(input(f'Digite a idade de {nome}: '))

if idade < 16:
  situacao = 'PROIBIDO'
elif idade >= 16 and idade < 18:
  situacao = 'OPTATIVO'
elif idade >= 18 and idade < 65:
  situacao = 'OBRIGATÓRIO'
else:
  situacao = 'OPTATIVO'

print(f'A situação de votação para {nome} é {situacao}.')

#  Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:
# “Telefonou para a vítima?"
# “Esteve no local do crime?"
# “Mora perto da vítima?""
# “Devia para a vítima?"
# “Já trabalhou com a vítima?"

# O programa deve no final emitir uma classificação sobre a participação da pessoa no crime.
# Se a pessoa responder positivamente a 2 questões ela deve ser classificada como “Suspeita”, entre 3 e 4 como “Cúmplice” e 5 como “Assassino“.
# Caso contrário, ele será classificado como “Inocente“.

print('-=' * 4)
print('DETETIVE')
print('=-' * 4)

classe = 0

#Primeira Quest
call = int(input('\nTelefonou para a vítima?\n'
                '[ 1 ] SIM\n'
                '[ 2 ] NÃO\n\n'))

#Enquanto o resultado não for entre 1 e 2
while call != 1 and call != 2:
  call = int(input('Digite um valor adequado!\n'))
if call == 1:
  classe +=1


#Segunda Quest
local = int(input('\nEsteve no local do crime?\n'
                '[ 1 ] SIM\n'
                '[ 2 ] NÃO\n\n'))

#Enquanto o resultado não for entre 1 e 2
while local != 1 and local != 2:
  local = int(input('Digite um valor adequado!\n'))
if local == 1:
  classe +=1


#Terceira Quest
moradia = int(input('\nMora perto da vítima?\n'
                '[ 1 ] SIM\n'
                '[ 2 ] NÃO\n\n'))

#Enquanto o resultado não for entre 1 e 2
while moradia != 1 and moradia != 2:
  moradia = int(input('Digite um valor adequado!\n'))
if moradia == 1:
  classe +=1


#Quarta Quest
devia = int(input('\nDevia para a vítima?\n'
                '[ 1 ] SIM\n'
                '[ 2 ] NÃO\n\n'))

#Enquanto o resultado não for entre 1 e 2
while devia != 1 and devia != 2:
  devia = int(input('Digite um valor adequado!\n'))
if devia == 1:
  classe +=1


#Quinta Quest
trabalhou = int(input('\nJá trabalhou com a vítima?\n'
                '[ 1 ] SIM\n'
                '[ 2 ] NÃO\n\n'))

#Enquanto o resultado não for entre 1 e 2
while trabalhou != 1 and trabalhou != 2:
  trabalhou = int(input('Digite um valor adequado!\n'))
if trabalhou == 1:
  classe +=1

if classe == 2:
  x = 'Suspeito'
elif classe == 3 or classe == 4:
  x = 'Cúmplice'
elif classe == 5:
  x = 'Assassino'
else:
  x = 'Inocente'

print(f'O usuário é considerado {x} por afirmar com {classe} questões levantadas.')

# Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato.
produtos = []
price = []

#Irá repetir conforme solicitado no range
for c in range(0, 3):
  #Inserindo o nome do produto
  produto = str(input('Digite o nome do produto: '))
  #Adicionando o nome na lista produtos
  produtos.append(produto)
  #Inserindo o preço do produto
  preco = float(input('Digite o preço: R$'))
  #Adicionando o preço na lista price
  price.append(preco)

#Definindo o menor valor da lista na variável x
x = min(price)
#Definindo a posição do preço mais barato na lista price
position = price.index(x)
#Como a posição dos nomes e dos preços estão em sequências com as posições, eu inseri a função index para procurar a mesma posição do preço para nome dos produtos.
print(f'O produto mais acessível é {produtos[position]}, que custa R${x:.2f}.')